using System.Diagnostics.CodeAnalysis;
using SlayRuneterra.Content.Epochs;

namespace SlayRuneterra.Utils.Epochs;


/// <summary>
/// THIS ENTIRE CLASS SHOULD BE AUTOGENERATED OR HANDLED COMPLETELY DIFFERENTLY IN A MODDED ENVIRONMENT
/// </summary>
public static class CustomEpochModelSubtypes
{
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
    private static readonly Type _t0 = typeof(TestEpoch);
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
    private static readonly Type _t1 = typeof(UprisingEpoch);
    
    
    
    private static readonly Type[] _subtypes = new Type[2]
    {
                _t0, _t1
    };
    public static int Count => 2;
    public static IReadOnlyList<Type> All => _subtypes;
    
    [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2063", Justification = "The list only contains types stored with the correct DynamicallyAccessedMembers attribute, enforced by source generation.")]
    [return: DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
    public static Type Get(int i)
    {
        return _subtypes[i];
    }
}